### ISSUE TITLE
Highlighting wrong when braces immediately adjacent to HTML content

### ISSUE THREAD

**Issue by mcandre** [atom/language-mustache#36] opened 2019-04-11 16:19 UTC
*Edit by @rsese to add template and screenshot*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

language-mustache is highlighting my HTML Mustache templates incorrectly.

```mustache
<p>Colors</p>
<select>
  <option value="1" {{ #sel }}selected{{ /sel }}>Green</option>
</select>
```

`/sel` inside of `{{ }}` is highlighting as an HTML attribute. As a workaround, I have to move `{{ /sel }}` an extra space after the actual `selected` HTML attribute.

### Steps to Reproduce

1. create a new file and set grammar to `HTML (Mustache)` with `Grammar Selector: Show`
2. copy/paste this code:

```mustache
<p>Colors</p>
<select>
  <option value="1" {{ #sel }}selected{{ /sel }}>Green</option>
</select>
```

**Expected behavior:** [What you expect to happen]

`/sel` inside of `{{ }}` is not highlighted as an HTML attribute.

**Actual behavior:** [What actually happens]

`/sel` inside of `{{ }}` is highlighting as an HTML attribute. As a workaround, I have to move `{{ /sel }}` an extra space after the actual `selected` HTML attribute.

![highlighting-issue](https://github-slack.s3.amazonaws.com/monosnap/untitled__worktest-tree-sitter_2019-04-23_22-05-05.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.38.0-nightly9 on macOS 10.12.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2019-04-24 20:00
Thanks @mcandre - reproduced with 1.38.0-nightly9 on macOS 10.12.6.  I edited the issue body to add the template details, please use the template for future issues.

**Comment by sadick254** [comment] 2021-05-05 11:22
Hey @mcandre,  I know this issue has been here for a long time now. It looks like you found the workaround for the syntax highlighting issue. Adding a space between  `selected` and the opening mustache template tags `{{`.

Looking at the sample code provided `<option value="1" {{ #sel }}selected{{ /sel }}>Green</option>` it looks like the goal is to remove extra space by  combining `{{ #sel }}selected{{ /sel }}`.

The generated output would look like `<option value="1" >Green</option>`_(notice the space before the closing tag)_  or `<option value="1" selected>Green</option>` based on the value of `sel`.

If we were to fix the issue, there are two things we could do 
- Update mustache grammar and define a new injection point regex to something like `\w+(?={{`) which would also mean updating the other patterns on the grammar file.
- Update the [html grammar ](https://github.com/atom/language-html/blob/master/grammars/html.cson#L572) and include `}` in the regex. We would also need to update html tree-sitter-specs that would fail as a result of that change.

IMO I don't see us getting more value by doing any of the options described above.

**Closed by sadick254** 2021-05-05 11:22 UTC
Labels: d ⬇️, i ⬇️, triaged, v ⬇️
